name: Build

on:
  [workflow_dispatch, push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3.3.0
      with:
        submodules: recursive
    
    - name: Build
      working-directory: ${{github.workspace}}/build
      env:
        CXX: clang++
      run: |
        cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_UTILS=ON
        cmake --build . --config $BUILD_TYPE -j4

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: ModelTest-${{ matrix.os }}
        path: ${{github.workspace}}/build/Utils/ModelTest
