name: Build

on:
  [workflow_dispatch, push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    name: Build Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [linux-x86_64]
    steps:
    - uses: actions/checkout@v3.3.0
      with:
        submodules: recursive
    
    - name: Build Plugin
      working-directory: ${{github.workspace}}/build
      env:
        CXX: clang++
      run: |
        cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
        cmake --build . --config $BUILD_TYPE -j4
        cpack

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: ModelTest-${{ matrix.target }}
        path: ${{github.workspace}}/build/Utils/ModelTest
